/* ------------------------------------------------------------------------------------------------------------------

                       Autora: Vitória Viana | vitoria@rapidonet.com.br
                       Empresa: Rapidonet Sistemas e Automação
					   
					   Software: FORACESSO
                       Data da última modificação: 24/05/2024

  Descrição: Algo com cartões temporários

------------------------------------------------------------------------------------------------------------------ */

SELECT  CONVERT(VARCHAR,REPLICATE(0,18-LEN(M.MATR_MATRICULA))+M.MATR_MATRICULA) "Matricula",
          REPLACE(CONVERT(VARCHAR,E.EVEN_MOMENTO,108), CHAR(58),''),
          REPLACE(CONVERT(VARCHAR,E.EVEN_MOMENTO,3),'/',''),
          E.COTR_CODIGO "COD_COLETOR",0,
          (SELECT TOP 1 EM.EMPR_CODIGO FROM FORACESSO.EMPRESA em  WHERE MA.EMPR_ID = EM.EMPR_ID) "COD_EMPRESA"
		  FROM FORACESSO.EVENTO E 
INNER JOIN FORACESSO.IDENTIFICACAO_MATRICULADO IM ON E.IDTF_CODIGO = IM.IDTF_CODIGO 
AND E.EVEN_MOMENTO BETWEEN IM.IDMT_INICIO AND isNull(ISNULL(IM.IDMT_BAIXA, IM.IDMT_VALIDADE), gEtdATe())
INNER JOIN FORACESSO.MATRICULADO M ON IM.MATR_ID = M.MATR_ID
INNER JOIN FORACESSO.MATRICULADO_ALOCACAO MA ON M.MATR_ID = MA.MATR_ID
WHERE E.COTR_CODIGO IN (26,27,29) 
AND IM.IDMT_TIPOUTILIZACAO in (2,3)
aNd COTR_CODIGO IN ('26','27','29') 
AND M.CNTR_ID IS NULL
AND E.EVEN_TIPO IN (17001,17004)
AND E.EVEN_MOMENTO BETWEEN :1DATAINI AND DATEADD(DAY,1, :2DATAFIM)
UNION
SELECT CONVERT(VARCHAR,REPLICATE(0,18-LEN('123666'))+'123666') "Matricula",
REPLACE(CONVERT(VARCHAR,E.EVEN_MOMENTO,108), CHAR(58),''),
REPLACE(CONVERT(VARCHAR,E.EVEN_MOMENTO,3),'/',''),
E.COTR_CODIGO "COD_COLETOR",0,
'40'
FROM 
FORACESSO.EVENTO E
JOIN FORACESSO.PESSOA P ON E.PESS_ID = P.PESS_ID
INNER JOIN FORACESSO.MATRICULADO M ON M.PESS_ID = E.PESS_ID AND M.MATR_ATIVO = '1'
AND M.MATR_ATIVO = '1' 
WHERE E.COTR_CODIGO IN ('26','27','29') 
AND E.MATR_IDVISITADO IS NOT NULL
AND E.EVEN_TIPO IN (17001,17004)
AND CONVERT(VARCHAR,E.EVEN_MOMENTO,103) >= :1DATAINI
AND CONVERT(VARCHAR,E.EVEN_MOMENTO,103) <= :2DATAFIM
ORDER BY 1,3,2